// api-dbs
// export const CategoryData = [
//   {
//     cate_id: 1,
//     cate_name: "Giới thiệu",
//     cate_href: "/gioithieu",
//   },
//   {
//     cate_id: 2,
//     cate_name: "Trang điểm",
//     cate_href: "/trangdiem",
//   },
//   {
//     cate_id: 3,
//     cate_name: "Chăm sóc da",
//     cate_href: "/chamsocda",
//   },
//   {
//     cate_id: 4,
//     cate_name: "Nước hoa",
//     cate_href: "/nuochoa",
//   },
//   {
//     cate_id: 5,
//     cate_name: "Gift set",
//     cate_href: "/giftset",
//   },
//   {
//     cate_id: 6,
//     cate_name: "Kiểm tra đơn hàng",
//     cate_href: "/ktdonhang",
//   },
// ];

export const ProData = [
  {
    pr_id: 1,
    pr_hot: 1,
    pr_image: "./images/sp1.jpeg",
    pr_brand: "Marc Jacobs",
    pr_name: "Nước Hoa Nữ Marc Jacobs Decadence - Eau De Parfum 50ML",
    pr_price: "2.610.000 đ",
    cate_id: 4,
  },
  {
    pr_id: 2,
    pr_hot: 1,
    pr_image: "./images/sp2.jpeg",
    pr_brand: "Innisfree",
    pr_name: "Kem chống nắng Innisfree Intensive Long Lasting Suncreen EX",
    pr_price: "195.000 đ",
    cate_id: 3,
  },
  {
    pr_id: 3,
    pr_hot: 1,
    pr_image: "./images/sp3.jpeg",
    pr_price: "275.000 đ",
    pr_brand: "3CE",
    pr_name: "Son 3CE Glaze Lip Tint New Motion",
    cate_id: 2,
  },
  {
    pr_id: 4,
    pr_hot: 0,
    pr_image: "./images/sp4.jpeg",
    pr_price: "555.000 đ",
    pr_brand: "THE LAB",
    pr_name: "Phấn Nước THE LAB #01 IVORY Trắng Tự Nhiên",
    cate_id: 2,
  },

  {
    pr_id: 5,
    pr_hot: 1,
    pr_image: "./images/sp5.jpeg",
    pr_price: "394.250 đ",
    pr_brand: "SENKA",
    pr_name: "Serum Senka Cấp Ẩm Chuyên Sâu 30ml",
    cate_id: 3,
  },
  {
    pr_id: 6,
    pr_hot: 0,
    pr_image: "./images/sp6.jpeg",
    pr_price: "85.000 đ",
    pr_brand: "Vacosi",
    pr_: "Phấn Má Vacosi Lolipop VP08 - 02 Sweet Orange",
    cate_id: 2,
  },
  {
    pr_id: 7,
    pr_hot: 1,
    pr_image: "./images/sp7.jpeg",
    pr_price: "144.000 đ",
    pr_brand: "St.Ives",
    pr_name:
      "Sữa tắm tẩy da chết St.Ives Chiết Xuất Cam Chanh Làm Sáng Da 473ml",
    cate_id: 3,
  },
  {
    pr_id: 8,
    pr_hot: 0,
    pr_image: "./images/sp8.png",
    pr_price: "75.000 đ",
    pr_brand: "Tonymoly",
    pr_name: "Kem Dưỡng Da Tay Tonymoly So Cool 30ml",
    cate_id: 3,
  },
  {
    pr_id: 9,
    pr_hot: 0,
    pr_image: "./images/set1.jpeg",
    pr_price: "730.000 đ",
    pr_brand: "Innisfree",
    pr_name:
      "Set Dưỡng Da Trà Xanh Innisfree Green Tea Balancing Skin Care Trio EX",
    cate_id: 5,
  },
  {
    pr_id: 10,
    pr_hot: 1,
    pr_image: "./images/set2.jpeg",
    pr_price: "390.000 đ",
    pr_brand: "3W",
    pr_name: "Set 3W Clinic Collagen White Skin Care",
    cate_id: 5,
  },
  {
    pr_id: 11,
    pr_hot: 0,
    pr_image: "./images/set3.jpeg",
    pr_price: "90.000 đ",
    pr_brand: "MS03",
    pr_name: "Hộp Quà MS03 - Hồng",
    cate_id: 5,
  },
  {
    pr_id: 12,
    pr_hot: 1,
    pr_image: "./images/set4.jpeg",
    pr_price: "90.000 đ",
    pr_brand: "MS01",
    pr_name: "Hộp Quà Đen Nơ Đỏ MS01",
    cate_id: 5,
  },
  {
    pr_id: 13,
    pr_hot: 0,
    pr_image: "./images/td1.jpeg",
    pr_price: "265.000 đ",
    pr_brand: "Etude House",
    pr_name: "Phấn Mắt 9 Ô Etude House Play Color Eyes Maple Road",
    cate_id: 2,
  },
  {
    pr_id: 14,
    pr_hot: 0,
    pr_image: "./images/td2.jpeg",
    pr_price: "359.000 đ",
    pr_brand: "Avene",
    pr_name: "Xịt Khoáng Avene 300ml (Chai)",
    cate_id: 2,
  },
  {
    pr_id: 15,
    pr_hot: 0,
    pr_image: "./images/td3.jpeg",
    pr_price: "198.500 đ",
    pr_brand: "Maybelline",
    pr_name: "Phấn Phủ Mịn Lì Fit Me Maybelline - 110",
    cate_id: 2,
  },
  {
    pr_id: 16,
    pr_hot: 1,
    pr_image: "./images/td4.jpeg",
    pr_price: "139.500 đ",
    pr_brand: "Dearmay",
    pr_name: "Gel kẻ mày Dearmay - Ash Brown (Chiếc)",
    cate_id: 2,
  },
  {
    pr_id: 17,
    pr_hot: 0,
    pr_image: "./images/td5.png",
    pr_price: "178.500 đ",
    pr_brand: "Romand",
    pr_name:
      "Son Thỏi Siêu Mịn Romand New Zero Matte Lipstick - 02 All That Jazz",
    cate_id: 2,
  },
  {
    pr_id: 18,
    pr_hot: 0,
    pr_image: "./images/cs1.jpeg",
    pr_price: "864.000 đ",
    pr_brand: "OBAGI",
    pr_name: "Dung Dịch Đặc Trị Mụn BHA OBAGI CLENZIderm MD Pore Therapy 148ml",
    cate_id: 3,
  },
  {
    pr_id: 19,
    pr_hot: 0,
    pr_image: "./images/cs2.jpeg",
    pr_price: "323.000 đ",
    pr_brand: "Hada Labo",
    pr_name: "Mặt Nạ Hada Labo Dưỡng Ẩm Da Chuyên Sâu 20 Miếng",
    cate_id: 3,
  },
  {
    pr_id: 20,
    pr_hot: 0,
    pr_image: "./images/cs3.jpeg",
    pr_price: "154.000 đ",
    pr_brand: "Organic",
    pr_name: "Tẩy Da Chết Body Organic Coffee & Sugar Body Scrub",
    cate_id: 3,
  },
  {
    pr_id: 21,
    pr_hot: 0,
    pr_image: "./images/cs4.jpeg",
    pr_price: "395.000 đ",
    pr_brand: "Vichy",
    pr_name: "Sữa rửa mặt Vichy Gel Sạch Sâu Giảm Bã Nhờn 200ml",
    cate_id: 3,
  },
  {
    pr_id: 22,
    pr_hot: 0,
    pr_image: "./images/nh1.png",
    pr_price: "1.395.000 đ",
    pr_brand: "Calvin Klein",
    pr_name: "Nước Hoa Calvin Klein Eternity Air For Women EDP 30ml",
    cate_id: 4,
  },
  {
    pr_id: 23,
    pr_hot: 0,
    pr_image: "./images/nh2.jpeg",
    pr_price: "2.214.000 đ",
    pr_brand: "Paco Rabanne",
    pr_name: "Nước hoa Paco Rabanne Pure XS For Her Edp 50ml",
    cate_id: 4,
  },
  {
    pr_id: 24,
    pr_hot: 0,
    pr_image: "./images/nh3.png",
    pr_price: "222.000 đ",
    pr_brand: "Michael Kors",
    pr_name: "Nước hoa Michael Kors Extreme Blue 10ml",
    cate_id: 4,
  },
];
